import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.4";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}});
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});if(req.method!=="POST")return json({error:"Method not allowed"},405);
 const url=Deno.env.get("SUPABASE_URL"),service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),openai=Deno.env.get("OPENAI_API_KEY");if(!url||!service||!openai)return json({error:"Automation drafting is not configured"},503);
 const token=(req.headers.get("Authorization")||"").replace("Bearer ","").trim();const admin=createClient(url,service,{auth:{persistSession:false}});const{data:auth}=await admin.auth.getUser(token);if(!auth.user)return json({error:"Invalid session"},401);const{data:profile}=await admin.from("profiles").select("role,is_active").eq("id",auth.user.id).maybeSingle();if(!profile?.is_active||!["admin","platform_admin","super_admin"].includes(profile.role))return json({error:"Platform admin access required"},403);
 const payload=await req.json().catch(()=>null) as {instruction?:string}|null;const instruction=payload?.instruction?.trim();if(!instruction||instruction.length<12||instruction.length>2000)return json({error:"Describe the automation in 12–2000 characters"},400);
 const schema={type:"object",additionalProperties:false,properties:{name:{type:"string"},description:{type:"string"},domain:{type:"string",enum:["company_merge","company_verification","contribution_review","notification","data_quality","care_network"]},trigger_key:{type:"string"},conditions:{type:"array",items:{type:"object",additionalProperties:false,properties:{field:{type:"string"},operator:{type:"string",enum:["equals","not_equals","contains","in","greater_than","less_than","exists"]},value:{anyOf:[{type:"string"},{type:"number"},{type:"boolean"},{type:"array",items:{type:"string"}}]}},required:["field","operator","value"]}},action_key:{type:"string"},action_configuration:{type:"object",additionalProperties:false,properties:{queue_execution:{type:"boolean"},notify_reviewers:{type:"boolean"}},required:["queue_execution","notify_reviewers"]},approval_mode:{type:"string",enum:["human","delegated","automatic"]},priority:{type:"integer",minimum:1,maximum:1000},safety_explanation:{type:"string"}},required:["name","description","domain","trigger_key","conditions","action_key","action_configuration","approval_mode","priority","safety_explanation"]};
 const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${openai}`,"Content-Type":"application/json"},body:JSON.stringify({model:Deno.env.get("OPENAI_AUTOMATION_MODEL")||"gpt-5.6-luna",instructions:"Translate the administrator instruction into one bounded Medicine Support Hub automation rule. Never create diagnosis, prescribing, dispensing, patient-data disclosure, credential changes, code deployment, deletion, or unreviewed public publication rules. Company merge automation may approve a request only into an audited execution queue. Return only the schema.",input:instruction,text:{format:{type:"json_schema",name:"platform_automation_rule",strict:true,schema}}})});
 if(!response.ok)return json({error:"OpenAI could not draft the rule",detail:(await response.text()).slice(0,400)},502);const result=await response.json();const output=result.output_text||result.output?.flatMap((item:any)=>item.content||[]).find((item:any)=>item.type==="output_text")?.text;if(!output)return json({error:"The model returned no structured rule"},502);let draft;try{draft=JSON.parse(output);}catch{return json({error:"The model response was not valid structured data"},502);}
 const{data:rule,error}=await admin.from("platform_automation_rules").insert({name:draft.name,description:`${draft.description}\nSafety: ${draft.safety_explanation}`,domain:draft.domain,trigger_key:draft.trigger_key,conditions:draft.conditions,action_key:draft.action_key,action_configuration:draft.action_configuration,approval_mode:draft.approval_mode,status:"draft",priority:draft.priority,natural_language_source:instruction,model_draft_metadata:{provider:"openai",model:result.model,response_id:result.id},created_by:auth.user.id}).select("*").single();if(error)return json({error:error.message},400);return json({rule});});
