import { useEffect, useState } from "react";
import { Check, Database, MapPin, UserRound, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { usePatientAuth } from "@/lib/patient-auth";

type QueueItem={id:string;title?:string;medicine_name?:string;full_name?:string;channel_name?:string;submission_kind?:string;created_at:string;file_names?:string[];description?:string};
export function AdminMedicineDataIntake(){const {supabaseFetch}=usePatientAuth();const [catalog,setCatalog]=useState<QueueItem[]>([]);const [distribution,setDistribution]=useState<QueueItem[]>([]);const [representatives,setRepresentatives]=useState<QueueItem[]>([]);const [notes,setNotes]=useState<Record<string,string>>({});const [busy,setBusy]=useState("");const [error,setError]=useState("");
 async function load(){try{const [a,b,c]=await Promise.all([supabaseFetch<QueueItem[]>("/rest/v1/medicine_catalog_submissions?select=id,title,medicine_name,submission_kind,description,file_names,created_at&status=in.(submitted,under_review)&order=created_at.asc"),supabaseFetch<QueueItem[]>("/rest/v1/medicine_distribution_availability?select=id,medicine_name,channel_name,created_at&status=in.(submitted,under_review)&order=created_at.asc"),supabaseFetch<QueueItem[]>("/rest/v1/company_area_representatives?select=id,full_name,created_at&status=in.(submitted,under_review)&order=created_at.asc")]);setCatalog(a||[]);setDistribution(b||[]);setRepresentatives(c||[])}catch(e){setError(e instanceof Error?e.message:"Could not load governed intake.")}}
 useEffect(()=>{void load()},[]);
 async function review(kind:"catalog"|"distribution"|"representative",id:string,decision:"approved"|"rejected"){setBusy(id);setError("");try{const endpoint=kind==="catalog"?"review_medicine_catalog_submission":kind==="distribution"?"review_medicine_distribution_submission":"review_company_area_representative";await supabaseFetch(`/rest/v1/rpc/${endpoint}`,{method:"POST",body:JSON.stringify({target_submission:id,decision,reviewer_notes:notes[id]?.trim()||null})});await load()}catch(e){setError(e instanceof Error?e.message:"Review failed.")}finally{setBusy("")}}
  const section=(title:string,icon:typeof Database,items:QueueItem[],kind:"catalog"|"distribution"|"representative")=>{const Icon=icon;return <Card><CardHeader><CardTitle className="flex items-center gap-2"><Icon className="h-5 w-5"/>{title} <span className="text-sm font-normal text-muted-foreground">({items.length})</span></CardTitle></CardHeader><CardContent className="space-y-3">{items.map(item=><div key={item.id} className="rounded-xl border p-4"><div className="font-semibold">{item.title||item.medicine_name||item.full_name}</div>{item.channel_name&&<div className="text-sm text-muted-foreground">{item.channel_name}</div>}{item.submission_kind&&<div className="text-xs text-muted-foreground">{String(item.submission_kind || "").replaceAll("_"," ")} · {item.file_names?.join(", ")||"No attachment"}</div>}<Textarea className="my-3 min-h-16" placeholder="Optional reviewer note" value={notes[item.id]||""} onChange={(e)=>setNotes(n=>({...n,[item.id]:e.target.value}))}/><div className="flex gap-2"><Button size="sm" disabled={busy===item.id} onClick={()=>void review(kind,item.id,"approved")}><Check className="mr-1 h-4 w-4"/>Approve</Button><Button size="sm" variant="destructive" disabled={busy===item.id} onClick={()=>void review(kind,item.id,"rejected")}><X className="mr-1 h-4 w-4"/>Reject</Button></div></div>)}{!items.length&&<p className="rounded-xl border border-dashed p-5 text-sm text-muted-foreground">No pending items.</p>}</CardContent></Card>};
 return <section className="mt-10"><h2 className="text-2xl font-bold">Medicine data, availability, and representative approvals</h2><p className="mt-2 text-sm text-muted-foreground">Visible to platform administrators and delegated users with the Industry Review permission.</p>{error&&<p className="mt-3 rounded-lg border border-destructive p-3 text-sm text-destructive">{error}</p>}<div className="mt-5 grid gap-5 xl:grid-cols-3">{section("Medicine additions and datasets",Database,catalog,"catalog")}{section("Distribution availability",MapPin,distribution,"distribution")}{section("Area representatives",UserRound,representatives,"representative")}</div></section>}
