import { useEffect, useState } from "react";
import { MapPin, MessageCircle, PackageCheck, UserRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { usePatientAuth } from "@/lib/patient-auth";

type Availability={id:string;medicine_name:string;channel_type:string;channel_name:string;country:string|null;governorate:string|null;city:string|null;area:string|null;availability_status:string;representative_name:string|null};
type Representative={id:string;organization_id:string;full_name:string;role_title:string|null;country:string|null;governorate:string|null;city:string|null;area:string|null};
export function CompanyDistributionNetwork({companyProfileId}:{companyProfileId:string}){
 const {isAuthenticated,session,supabaseFetch}=usePatientAuth(); const [items,setItems]=useState<Availability[]>([]);const [reps,setReps]=useState<Representative[]>([]);const [selected,setSelected]=useState<Representative|null>(null);const [subject,setSubject]=useState("");const [body,setBody]=useState("");const [message,setMessage]=useState("");
 useEffect(()=>{Promise.all([supabaseFetch<Availability[]>(`/rest/v1/medicine_distribution_availability?select=id,medicine_name,channel_type,channel_name,country,governorate,city,area,availability_status,representative_name&company_profile_id=eq.${companyProfileId}&status=eq.approved&order=created_at.desc&limit=50`),supabaseFetch<Representative[]>(`/rest/v1/company_area_representatives?select=id,organization_id,full_name,role_title,country,governorate,city,area&company_profile_id=eq.${companyProfileId}&status=eq.approved&is_public=eq.true&order=full_name`)]).then(([a,r])=>{setItems(Array.isArray(a)?a:[]);setReps(Array.isArray(r)?r:[])}).catch(()=>{});},[companyProfileId,supabaseFetch]);
 async function send(e:React.FormEvent){e.preventDefault();if(!selected||!session?.user?.id)return;try{await supabaseFetch("/rest/v1/company_representative_messages",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({representative_id:selected.id,organization_id:selected.organization_id,sender_user_id:session.user.id,subject,body})});setSubject("");setBody("");setSelected(null);setMessage("Your private message was sent through Medicine Support Hub.");}catch(error){setMessage(error instanceof Error?error.message:"Message could not be sent.")}}
 if(!items.length&&!reps.length)return null;
 return <section className="mt-8 scroll-mt-28" id="distribution-network"><div className="mb-4"><h2 className="text-2xl font-bold">Availability and local representatives</h2><p className="text-sm text-muted-foreground">Approved distribution information submitted by the company and reviewed by the platform.</p></div><div className="grid gap-5 lg:grid-cols-2">
  {items.length>0&&<Card><CardHeader><CardTitle className="flex items-center gap-2"><PackageCheck className="h-5 w-5"/>Medicine availability</CardTitle></CardHeader><CardContent className="space-y-3">{items.map((item)=><div key={item.id} className="rounded-xl border p-3"><div className="font-semibold">{item.medicine_name}</div><div className="mt-1 text-sm">{item.channel_name} · {humanize(item.channel_type)}</div><div className="mt-1 flex items-center gap-1 text-xs text-muted-foreground"><MapPin className="h-3.5 w-3.5"/>{[item.area,item.city,item.governorate,item.country].filter(Boolean).join(", ")||"Area not specified"}</div><div className="mt-2 text-xs font-semibold text-primary">{humanize(item.availability_status)}</div></div>)}</CardContent></Card>}
  {reps.length>0&&<Card><CardHeader><CardTitle className="flex items-center gap-2"><UserRound className="h-5 w-5"/>Area representatives</CardTitle></CardHeader><CardContent className="space-y-3">{reps.map((rep)=><div key={rep.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-3"><div><div className="font-semibold">{rep.full_name}</div><div className="text-sm text-muted-foreground">{rep.role_title||"Company representative"}</div><div className="mt-1 text-xs">{[rep.area,rep.city,rep.governorate,rep.country].filter(Boolean).join(", ")}</div></div><Button type="button" variant="outline" size="sm" onClick={()=>setSelected(rep)}><MessageCircle className="mr-2 h-4 w-4"/>Message</Button></div>)}</CardContent></Card>}
 </div>{selected&&<Card className="mt-5 border-primary/30"><CardHeader><CardTitle>Message {selected.full_name}</CardTitle></CardHeader><CardContent>{!isAuthenticated?<Button asChild><a href={`/account?next=${encodeURIComponent(window.location.pathname+"#distribution-network")}`}>Sign in to message</a></Button>:<form onSubmit={send} className="space-y-3"><div><Label>Subject</Label><Input className="mt-1" value={subject} onChange={(e)=>setSubject(e.target.value)} minLength={3} required/></div><div><Label>Message</Label><Textarea className="mt-1 min-h-24" value={body} onChange={(e)=>setBody(e.target.value)} minLength={5} required/></div><div className="flex gap-2"><Button>Send private message</Button><Button type="button" variant="outline" onClick={()=>setSelected(null)}>Cancel</Button></div></form>}</CardContent></Card>}{message&&<p className="mt-3 rounded-lg border p-3 text-sm">{message}</p>}</section>
}
function humanize(v:string){return v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase())}
