import { useState } from "react";
import { MapPin, Send, UserRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { usePatientAuth } from "@/lib/patient-auth";
import type { ManagedCompany } from "@/components/medicine-data-contribution-hub";

export function CompanyDistributionManager({ companies }: { companies: ManagedCompany[] }) {
  const { session, supabaseFetch } = usePatientAuth();
  const [companyId, setCompanyId] = useState(companies[0]?.id || "");
  const [mode, setMode] = useState<"availability" | "representative">("availability");
  const [form, setForm] = useState<Record<string,string>>({ channel_type:"pharmacy", availability_status:"available" });
  const [busy,setBusy]=useState(false); const [message,setMessage]=useState("");
  const company=companies.find((item)=>item.id===companyId) || companies[0];
  const set=(key:string,value:string)=>setForm((current)=>({...current,[key]:value}));
  async function submit(event:React.FormEvent){event.preventDefault();if(!company||!session?.user?.id)return;setBusy(true);setMessage("");try{
    if(mode==="availability") await supabaseFetch("/rest/v1/medicine_distribution_availability",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({company_profile_id:company.id,organization_id:company.organization_id,submitted_by:session.user.id,medicine_name:form.medicine_name,channel_type:form.channel_type,channel_name:form.channel_name,country:form.country||null,governorate:form.governorate||null,city:form.city||null,area:form.area||null,availability_status:form.availability_status,source_url:normalizeUrl(form.source_url),representative_name:form.representative_name||null,representative_email:form.representative_email||null,representative_phone:form.representative_phone||null})});
    else await supabaseFetch("/rest/v1/company_area_representatives",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({company_profile_id:company.id,organization_id:company.organization_id,submitted_by:session.user.id,full_name:form.full_name,role_title:form.role_title||null,country:form.country||null,governorate:form.governorate||null,city:form.city||null,area:form.area||null,email:form.email||null,phone:form.phone||null,whatsapp_phone:form.whatsapp_phone||null,channels:[form.channel_type||"pharmacy"]})});
    setMessage("Submitted for approval. It will appear publicly only after an authorized reviewer approves it.");setForm({channel_type:"pharmacy",availability_status:"available"});
  }catch(error){setMessage(error instanceof Error?error.message:"Submission failed.");}finally{setBusy(false);}}
  return <Card className="border-primary/20"><CardHeader><CardTitle className="flex items-center gap-2"><MapPin className="h-5 w-5 text-primary"/>Distribution availability and area representatives</CardTitle><p className="text-sm text-muted-foreground">Publish where medicines are available and who represents your company in each area. Every entry is reviewed before it becomes public.</p></CardHeader><CardContent>
    <div className="mb-5 grid gap-2 sm:grid-cols-2"><Button type="button" variant={mode==="availability"?"default":"outline"} onClick={()=>setMode("availability")}>Medicine availability</Button><Button type="button" variant={mode==="representative"?"default":"outline"} onClick={()=>setMode("representative")}><UserRound className="mr-2 h-4 w-4"/>Area representative</Button></div>
    <form onSubmit={submit} className="space-y-4"><Field label="Company"><select className="h-11 w-full rounded-md border bg-background px-3" value={companyId} onChange={(e)=>setCompanyId(e.target.value)}>{companies.map((item)=><option key={item.id} value={item.id}>{item.display_name}</option>)}</select></Field>
      {mode==="availability"?<><div className="grid gap-4 md:grid-cols-2"><Text label="Medicine name" value={form.medicine_name} onChange={(v)=>set("medicine_name",v)} required/><Field label="Supply channel"><select className="h-11 w-full rounded-md border bg-background px-3" value={form.channel_type} onChange={(e)=>set("channel_type",e.target.value)}><option value="pharmacy">Pharmacy</option><option value="pharmaceutical_warehouse">Pharmaceutical warehouse</option><option value="pharmaceutical_distributor">Distribution company</option></select></Field><Text label="Pharmacy, warehouse, or distributor name" value={form.channel_name} onChange={(v)=>set("channel_name",v)} required/><Field label="Availability"><select className="h-11 w-full rounded-md border bg-background px-3" value={form.availability_status} onChange={(e)=>set("availability_status",e.target.value)}><option value="available">Available</option><option value="limited">Limited</option><option value="out_of_stock">Out of stock</option><option value="preorder">Pre-order</option></select></Field></div></>:<div className="grid gap-4 md:grid-cols-2"><Text label="Representative full name" value={form.full_name} onChange={(v)=>set("full_name",v)} required/><Text label="Role or territory title" value={form.role_title} onChange={(v)=>set("role_title",v)}/><Text label="Email" type="email" value={form.email} onChange={(v)=>set("email",v)}/><Text label="Phone" type="tel" value={form.phone} onChange={(v)=>set("phone",v)} required/><Text label="WhatsApp" type="tel" value={form.whatsapp_phone} onChange={(v)=>set("whatsapp_phone",v)}/></div>}
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Text label="Country" value={form.country} onChange={(v)=>set("country",v)}/><Text label="Governorate / region" value={form.governorate} onChange={(v)=>set("governorate",v)}/><Text label="City" value={form.city} onChange={(v)=>set("city",v)}/><Text label="Area" value={form.area} onChange={(v)=>set("area",v)}/></div>
      {mode==="availability"&&<><Text label="Official source URL" value={form.source_url} onChange={(v)=>set("source_url",v)}/><div className="grid gap-4 md:grid-cols-3"><Text label="Local representative" value={form.representative_name} onChange={(v)=>set("representative_name",v)}/><Text label="Representative email" type="email" value={form.representative_email} onChange={(v)=>set("representative_email",v)}/><Text label="Representative phone" type="tel" value={form.representative_phone} onChange={(v)=>set("representative_phone",v)}/></div></>}
      {message&&<p className="rounded-lg border bg-muted/30 p-3 text-sm">{message}</p>}<Button disabled={busy}><Send className="mr-2 h-4 w-4"/>{busy?"Submittingâ€¦":"Submit for approval"}</Button></form>
  </CardContent></Card>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div><Label>{label}</Label><div className="mt-1">{children}</div></div>}
function Text({label,value,onChange,type="text",required=false}:{label:string;value?:string;onChange:(v:string)=>void;type?:string;required?:boolean}){return <div><Label>{label}</Label><Input className="mt-1" type={type} value={value||""} onChange={(e)=>onChange(e.target.value)} required={required}/></div>}
function normalizeUrl(value?:string){const v=value?.trim();return !v?null:/^[a-z][a-z\d+.-]*:\/\//i.test(v)?v:`https://${v}`}
