create index if not exists medicine_collaboration_submissions_reviewed_by_idx
  on public.medicine_collaboration_submissions (reviewed_by)
  where reviewed_by is not null;

alter table public.medicines5
  add column if not exists source_row_id bigint generated by default as identity;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conrelid = 'public.medicines5'::regclass
      and contype = 'p'
  ) then
    alter table public.medicines5
      add constraint medicines5_pkey primary key (source_row_id);
  end if;
end;
$$;
