-- Additive schema for source-backed medicines2 enrichment.
-- Raw medicines3/medicines4 data remains private.

create extension if not exists pg_trgm;

create or replace function public.normalize_catalog_name(value text)
returns text language sql immutable parallel safe set search_path = public as $$
  select regexp_replace(
    lower(translate(coalesce(value, ''), 'أإآٱةىؤئًٌٍَُِّْـ', 'ااااهيوي')),
    '[^a-z0-9ء-ي]+', '', 'g'
  );
$$;

create or replace function public.normalize_ascii_catalog_name(value text)
returns text language sql immutable parallel safe set search_path = public as $$
  select regexp_replace(lower(coalesce(value, '')), '[^a-z0-9]+', '', 'g');
$$;

create or replace function public.catalog_number_signature(value text)
returns text language sql immutable parallel safe set search_path = public as $$
  select regexp_replace(coalesce(value, ''), '[^0-9]+', '', 'g');
$$;

create or replace function public.canonical_source_url(value text)
returns text language sql immutable parallel safe set search_path = public as $$
  select nullif(split_part(trim(coalesce(value, '')), ' ', 1), '');
$$;

create or replace function public.clean_netmeds_generic(value text)
returns text language sql immutable parallel safe set search_path = public as $$
  select nullif(trim(
    regexp_replace(
      regexp_replace(coalesce(value, ''), '^\s*Generic Name\s*', '', 'i'),
      '\s+Also Known As:.*$', '', 'i'
    )
  ), '');
$$;

create table if not exists public.medicine_catalog_source_evidence (
  id bigint generated by default as identity primary key,
  source_system text not null check (source_system in ('egyptdwa', 'netmeds')),
  source_key text not null,
  medicines2_id bigint not null references public.medicines2(id) on delete cascade,
  match_method text not null,
  confidence text not null default 'verified'
    check (confidence in ('verified', 'review_required', 'rejected')),
  match_score numeric(6,5),
  source_name text,
  source_url text,
  image_url text,
  category_name text,
  category_url text,
  product_views bigint,
  category_views bigint,
  observed_price numeric(18,3),
  observed_price_text text,
  observed_currency text,
  generic_name text,
  disease_area text,
  prescription_required text,
  manufacturer_name text,
  manufacturer_origin text,
  evidence jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (source_system, source_key),
  unique (source_system, medicines2_id)
);

comment on table public.medicine_catalog_source_evidence is
  'Verified, attributed source evidence linked to medicines2 without changing catalog identity or price.';
comment on column public.medicine_catalog_source_evidence.observed_price is
  'Source-observed value only; never overrides medicines2.price.';

create index if not exists medicine_catalog_source_evidence_product_idx
  on public.medicine_catalog_source_evidence(medicines2_id, source_system)
  where confidence = 'verified';
create index if not exists medicine_catalog_source_evidence_source_idx
  on public.medicine_catalog_source_evidence(source_system, confidence);

alter table public.medicine_catalog_source_evidence enable row level security;
drop policy if exists medicine_catalog_source_evidence_public_read
  on public.medicine_catalog_source_evidence;
create policy medicine_catalog_source_evidence_public_read
  on public.medicine_catalog_source_evidence
  for select to anon, authenticated
  using (confidence = 'verified');
revoke all privileges on table public.medicine_catalog_source_evidence from anon, authenticated;
grant select on public.medicine_catalog_source_evidence to anon, authenticated;

create table if not exists public.international_ingredient_reference (
  ingredient_key text primary key,
  ingredient_name text not null,
  source_system text not null default 'netmeds' check (source_system = 'netmeds'),
  source_product_count bigint not null,
  disease_areas text[] not null default '{}',
  prescription_required_observed boolean not null default false,
  manufacturer_sample text,
  manufacturer_origin_sample text,
  source_url_sample text,
  updated_at timestamptz not null default now()
);

alter table public.international_ingredient_reference enable row level security;
drop policy if exists international_ingredient_reference_public_read
  on public.international_ingredient_reference;
create policy international_ingredient_reference_public_read
  on public.international_ingredient_reference
  for select to anon, authenticated using (true);
revoke all privileges on table public.international_ingredient_reference from anon, authenticated;
grant select on public.international_ingredient_reference to anon, authenticated;

-- Do not expose raw imports. medicines4 includes long-form third-party clinical text
-- and foreign-market prices that are unsuitable as direct application records.
alter table public.medicines3 enable row level security;
alter table public.medicines4 enable row level security;
revoke all privileges on table public.medicines3 from anon, authenticated;
revoke all privileges on table public.medicines4 from anon, authenticated;
