import { ExternalLink, Info, ShieldCheck } from "lucide-react";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { useLanguage } from "@/lib/i18n";

const AMAZON_URL="https://www.amazon.com?&linkCode=ll2&tag=jesussavedm03-20&linkId=9595e25fcf981157824faa0db82976e2&language=en_US&ref_=as_li_ss_tl";
const AMAZON_INDIA_URL="https://www.amazon.in/?tag=jesussavedmin-21";
export default function MonetizationDisclosure(){
 const{t}=useLanguage();
 return <main className="container mx-auto max-w-5xl px-4 py-10"><section className="rounded-3xl border bg-card p-6 shadow-sm md:p-8"><p className="flex items-center gap-2 text-sm font-semibold uppercase tracking-wide text-primary"><ShieldCheck className="h-4 w-4"/>{t("Transparency","الشفافية")}</p><h1 className="mt-3 text-3xl font-bold">{t("Advertising and affiliate disclosure","إفصاح الإعلانات والروابط التابعة")}</h1><p className="mt-3 max-w-3xl text-muted-foreground">{t("Advertising and affiliate relationships help support platform operations. Commercial content never changes medicine facts, source attribution, moderation, clinical warnings, or marketplace verification rules.","تساعد الإعلانات والروابط التابعة في دعم تشغيل المنصة، ولا تغيّر المحتوى التجاري حقائق الأدوية أو نسب المصادر أو الإشراف أو التحذيرات السريرية أو قواعد توثيق السوق.")}</p></section>
  <div className="mt-6 grid gap-5 md:grid-cols-2"><Card><CardHeader><CardTitle>{t("Google advertising","إعلانات Google")}</CardTitle></CardHeader><CardContent className="space-y-3 text-sm leading-6 text-muted-foreground"><p>{t("This site uses Google AdSense. Google and its partners may use cookies or similar technologies to deliver, measure, and personalize ads where permitted by your choices and applicable law.","يستخدم هذا الموقع Google AdSense، وقد تستخدم Google وشركاؤها ملفات تعريف الارتباط أو تقنيات مشابهة لعرض الإعلانات وقياسها وتخصيصها حيث تسمح اختياراتك والقانون المعمول به.")}</p><a className="inline-flex font-semibold text-primary" href="https://policies.google.com/technologies/partner-sites" target="_blank" rel="noopener noreferrer">{t("How Google uses partner-site data","كيفية استخدام Google لبيانات مواقع الشركاء")}<ExternalLink className="ml-2 h-4 w-4"/></a></CardContent></Card>
   <Card><CardHeader><CardTitle>{t("Amazon Associates","برنامج Amazon Associates")}</CardTitle></CardHeader><CardContent className="space-y-3 text-sm leading-6 text-muted-foreground"><p>{t("Medicine Support Hub may earn a commission from qualifying purchases made through eligible Amazon links, at no additional cost to the purchaser.","قد تحصل منصة دعم الدواء على عمولة من المشتريات المؤهلة عبر روابط Amazon التابعة دون تكلفة إضافية على المشتري.")}</p><div className="flex flex-wrap gap-2"><Button asChild><a href={AMAZON_URL} target="_blank" rel="sponsored nofollow noopener noreferrer">{t("Visit Amazon.com","زيارة Amazon.com")}<ExternalLink className="ml-2 h-4 w-4"/></a></Button><Button asChild variant="outline"><a href={AMAZON_INDIA_URL} target="_blank" rel="sponsored nofollow noopener noreferrer">{t("Visit Amazon India","زيارة Amazon India")}<ExternalLink className="ml-2 h-4 w-4"/></a></Button></div></CardContent></Card></div>
  <Alert className="mt-6"><Info className="h-4 w-4"/><AlertDescription>{t("Advertisements and affiliate links are not endorsements, prescriptions, clinical recommendations, or proof of product quality or availability. Always verify seller, product, licensing, suitability, and safety independently.","الإعلانات والروابط التابعة ليست تأييدًا أو وصفة أو توصية سريرية أو دليلًا على جودة المنتج أو توافره. تحقق بشكل مستقل من البائع والمنتج والترخيص والملاءمة والسلامة.")}</AlertDescription></Alert></main>;
}
