/**
 * Canonical ID mapping: static dataset IDs → live Appwrite medicines IDs.
 *
 * Generated by: node scripts/map-static-to-live-ids.mjs [--write]
 * Public file:  /data/static-to-live-id-map.json
 *
 * Duplicate trade names are listed in `ambiguous_names` and are NOT resolved
 * by name alone (avoids wrong monograph).
 */

import { normalizeTradeName } from "./catalog-links";

export type AccuracySummary = {
  accuracy_score_percent?: number;
  matched_count?: number;
  unmatched_count?: number;
  ambiguous_count?: number;
  confidence?: {
    average?: number;
    high_ge_0_9?: number;
    medium_0_7_to_0_9?: number;
    low_lt_0_7?: number;
  };
  pass?: boolean;
  generated_at?: string;
};

export type CanonicalIdMapFile = {
  version: number;
  generated_at?: string | null;
  static_to_live: Record<string, number>;
  name_to_live: Record<string, number>;
  ambiguous_names?: Record<string, number[]>;
  accuracy_summary?: AccuracySummary;
  stats?: Record<string, number | undefined>;
};

export type CanonicalIdMapStatus =
  | "idle"
  | "loading"
  | "ready"
  | "empty"
  | "error";

type StatusListener = (s: CanonicalIdMapStatus, err: string | null) => void;

let cache: CanonicalIdMapFile | null = null;
let loadPromise: Promise<CanonicalIdMapFile | null> | null = null;
let status: CanonicalIdMapStatus = "idle";
let lastError: string | null = null;
const listeners = new Set<StatusListener>();

const EMPTY: CanonicalIdMapFile = {
  version: 1,
  static_to_live: {},
  name_to_live: {},
  ambiguous_names: {},
};

function setStatus(next: CanonicalIdMapStatus, err: string | null = null) {
  status = next;
  lastError = err;
  listeners.forEach((fn) => {
    try {
      fn(next, err);
    } catch {
      /* ignore listener errors */
    }
  });
}

function isValidMap(data: unknown): data is CanonicalIdMapFile {
  if (!data || typeof data !== "object") return false;
  const d = data as CanonicalIdMapFile;
  return (
    typeof d.static_to_live === "object" &&
    d.static_to_live !== null &&
    typeof d.name_to_live === "object" &&
    d.name_to_live !== null
  );
}

export function getCanonicalIdMapStatus(): CanonicalIdMapStatus {
  return status;
}

export function getCanonicalIdMapError(): string | null {
  return lastError;
}

export function getCanonicalIdMapSnapshot(): CanonicalIdMapFile | null {
  return cache;
}

export function subscribeCanonicalIdMapStatus(fn: StatusListener): () => void {
  listeners.add(fn);
  fn(status, lastError);
  return () => {
    listeners.delete(fn);
  };
}

export async function loadCanonicalIdMap(): Promise<CanonicalIdMapFile> {
  if (cache && status === "ready") return cache;
  if (loadPromise) {
    const m = await loadPromise;
    return m || EMPTY;
  }

  setStatus("loading");

  loadPromise = (async () => {
    try {
      const res = await fetch("/data/static-to-live-id-map.json", {
        cache: "no-cache",
      });
      if (!res.ok) {
        setStatus("error", `Could not load ID map (HTTP ${res.status})`);
        return EMPTY;
      }
      let data: unknown;
      try {
        data = await res.json();
      } catch {
        setStatus("error", "ID map file is not valid JSON");
        return EMPTY;
      }
      if (!isValidMap(data)) {
        setStatus("error", "ID map schema is invalid");
        return EMPTY;
      }

      cache = {
        version: data.version || 1,
        generated_at: data.generated_at,
        static_to_live: data.static_to_live || {},
        name_to_live: data.name_to_live || {},
        ambiguous_names: data.ambiguous_names || {},
        accuracy_summary: data.accuracy_summary,
        stats: data.stats,
      };

      const mapped = Object.keys(cache.static_to_live).length;
      if (mapped > 0) {
        setStatus("ready");
      } else {
        setStatus(
          "empty",
          "ID map is empty — run export + map-static-to-live-ids.mjs",
        );
      }
      return cache;
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      setStatus("error", msg);
      console.warn("[canonical-id-map]", msg);
      return EMPTY;
    } finally {
      if (status === "error" || status === "empty") {
        loadPromise = null;
      }
    }
  })();

  return (await loadPromise) || EMPTY;
}

export function isAmbiguousName(name: string | null | undefined): boolean {
  if (!cache?.ambiguous_names || !name) return false;
  const key = normalizeTradeName(name);
  return Boolean(key && cache.ambiguous_names[key]?.length);
}

export function getAmbiguousLiveIds(
  name: string | null | undefined,
): number[] {
  if (!cache?.ambiguous_names || !name) return [];
  const key = normalizeTradeName(name);
  return cache.ambiguous_names[key] || [];
}

export function resolveLiveCanonicalIdSync(options: {
  staticId?: number | string | null;
  nameEn?: string | null;
  nameAr?: string | null;
}): number | null {
  if (!cache) return null;
  const { staticId, nameEn, nameAr } = options;

  try {
    if (staticId != null && String(staticId).trim() !== "") {
      const key = String(staticId);
      const live = cache.static_to_live[key];
      if (live != null && Number.isFinite(Number(live))) return Number(live);
    }

    if (isAmbiguousName(nameEn) || isAmbiguousName(nameAr)) {
      return null;
    }

    const ne = normalizeTradeName(nameEn || "");
    if (ne && cache.name_to_live[ne] != null) {
      const id = Number(cache.name_to_live[ne]);
      if (Number.isFinite(id)) return id;
    }
    const na = normalizeTradeName(nameAr || "");
    if (na && cache.name_to_live[na] != null) {
      const id = Number(cache.name_to_live[na]);
      if (Number.isFinite(id)) return id;
    }
  } catch (err) {
    console.warn("[canonical-id-map] resolve error", err);
  }

  return null;
}

export async function resolveLiveCanonicalId(options: {
  staticId?: number | string | null;
  nameEn?: string | null;
  nameAr?: string | null;
}): Promise<number | null> {
  try {
    await loadCanonicalIdMap();
    return resolveLiveCanonicalIdSync(options);
  } catch (err) {
    console.warn("[canonical-id-map] async resolve failed", err);
    return null;
  }
}

export function prefetchCanonicalIdMap(): void {
  void loadCanonicalIdMap().catch((err) => {
    console.warn("[canonical-id-map] prefetch failed", err);
  });
}

/** Force reload (e.g. after ops regenerates the map). */
export function resetCanonicalIdMapCache(): void {
  cache = null;
  loadPromise = null;
  setStatus("idle");
}
